export const actorMemories = {
    addItemsResponse: 'addItemsResponse',
    address : 'addressData',
    addressResponse : 'addressResponse',
    autocompleteResponse : 'autocompleteResponse',
    brandsAdsSectionResponse : 'brandsAdsSectionResponse',
    bannersSectionResponseList : 'bannersSectionResponseList',
    customToken : 'customToken',
    country : 'country',
    countryId : 'countryId',
    checkoutDeliveryAddress : 'checkoutDeliveryAddress',
    checkoutOrderTotalValue : 'checkoutOrderTotalValue',
    checkoutPaymentMethod : 'checkoutPaymentMethod',
    checkoutResponse : 'checkoutResponse',
    checkoutSuggestedDate : 'checkoutSuggestedDate',
    currentTotalBalanceValue : 'currentTotalBalanceValue',
    dayOfferSectionResponse : 'dayOfferSectionResponse',
    discountsSectionResponse : 'discountedSectionResponse',
    ecommerceDataTableSections : 'ecommerceDataTableSections',
    ecommerceHomeSections : 'ecommerceHomeSections',
    favoritesSectionResponse : 'favoritesSectionResponse',
    hasCoverageResponse : 'hasCoverageResponse',
    idToken : 'idToken',
    initialQuantity : 'initialQuantity',
    latitude : 'lat',
    localId : 'localId',
    locationId : 'locationId',
    longitude : 'long',
    macroCategoriesSectionResponse : 'macroCategoriesSectionResponse',
    minimunOrderCondition: 'condition',
    minOrderValue: 'minOrderValue',
    newReferencesSectionResponse : 'newReferencesSectionResponse',
    offersContentSectionResponseList : 'offersContentSectionResponseList',
    orderId : 'orderId',
    orderCheckDataResponse : 'orderCheckDataResponse',
    otp : 'otp',
    phone : 'phone',
    phoneCode : 'phone Code',
    productName : 'productName',
    productsFound : 'productsFound',
    productsFromSearchBar : 'productsFromSearchBar',
    purchaseResponse : 'purchaseResponse',
    purchaseUid : 'purchaseUid',
    quantityDecreased : 'quantityDecreased',
    quantityIncreased : 'quantityIncreased',
    randomIncrease : 'randomIncrease',
    searchResponse : 'searchResponse',
    sectionBannerAccess: 'sectionBannerAccess',
    sectionCombosAndOffersAccess: 'sectionCombosAndOffersAccess',
    shoppingCartSubtotal : 'shoppingCartSubtotal',
    shoppingCartResponse : 'shoppingCartResponse',
    shoppingCartTotalDec : 'shoppingCartTotalDec',
    shoppingCartTotalInc : 'shoppingCartTotalInc',
    shoppingCartUnitPrice: 'shoppingCartUnitPrice',
    startSignUpResponse : 'startSignUpResponse',
    storeId : 'storeId',
    subcategoryList : 'subcategoryList',
    timeResponse : 'timeResponse',
    topForYouSectionResponse : 'topForYouSectionResponse',
    topSellerSectionResponse : 'topSellerSectionResponse',
    unbeatableSectionResponse : 'unbeatableSectionResponse',
    userId : 'userId',
    warehouseIds : 'warehouseIds',        

    //Common Vivo Endpoints
    availableProduct : 'availableProducts'
}