export const constants = {
    'apiDefaultTimeOut' : 30000,
    'additionalInfoAddress' : 'TAE Execution',  
    'addressColombia' : `Calle ${Math.floor(Math.random() * 100) + 10} #${Math.floor(Math.random() * 100)}-${Math.floor(Math.random() * 100)} Bogotá`, 
    'addressMexico' : `Donceles ${Math.floor(Math.random() * 100) + 10}, Centro, 06000 Cuauhtémoc`,
    'addressBrazil' : ``,
    'banners' : 'Banners',
    'brazilAsACountry': 'Brasil',
    'bogota': 'Bogota',
    'callChannel' : 'llamada',
    'call' : 'call',
    'colombiaAsACountry': 'Colombia',
    'ElementDefaultTimeOuts' : 59,
    'ecommerceUrl': 'staging.chiper.co/',
    'indexAutocomplete' : 0,
    'invalidOtp' : '0101',
    'macrocategories' : 'Macrocategories',
    'mexicoAsACountry': 'México',
    'moneyRegexp' : /[\s.]/g,
    'newUserFirstName':`TaeName${Math.floor(Math.random() * 100000)}`,
    'newUserLastName':`TaeLastName${Math.floor(Math.random() * 100000)}`,
    'newUserStoreName':`TaeStoreName${Math.floor(Math.random() * 100000)}`,
    'newUserBussinessAddress':`Carrera 24 # 6 - 225 Madrid`,
    'newUserBussinessAddressDetails' : 'Torre 4 Apartamento 306',
    'reserveUid' : '8893ba83-c641-401c-b3b6-539875cfd0da',
    'operationalUrl' : 'operaciones.chiper.co/',
    'orderPaymentValueRegexp' : /[\s$.]/g,
    'orderTrackingOrderCreated' : 'OrderCreated',
    'orderTrackingReceivedState' : 'Received',
    'productName' : 'Whisky',
    'purchaseFrom': 'search bar product show',
    'purchaseProcessedStatus' : 'PROCESSED',
    'queryTypeInsert' : 'insert',
    'searchVersion' : '1.0.0',
    'shoppingCartIsMajorToMinOrderValue': 'major',
    'shoppingCartIsPossibleToCreateOrder': 'can be',
    'shoppingCartOkStatus' : 'OK',
    'sessionId' : 'vnwoyr9gq6pi6b0hxob5y-1681742416541',
    'surchargesData' : 1000,
    'smsChannel' : 'sms',
    'vivoLoginUrlRedirected' : '/auth/sign-in',
    'whatsappChannel' : 'whatsapp',    
    'whatsapp' : 'wa',
    'web' : 'web',

    //Common Vivo
    'applicationName' : 'VIVO_WEB',
    'macroNameLiquor' : 'Licores'
}